name: JDKBuilds

on:
  push:
    branches:
      - master
      - 'releases/*'
  pull_request:
    branches:
      - '*'

jobs:
  openjdk:
    strategy:
      matrix:
        jdk: [8-slim, 11-slim, 13, 14]
    name: "OpenJDK ${{ matrix.jdk }}"
    runs-on: ubuntu-latest
    container: "maven:3.6.2-${{ matrix.jdk }}"
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: mvn -V --no-transfer-progress clean verify -Prun-its -Drat.ignoreErrors=true -Dmaven.test.failure.ignore -Dcheckstyle.skip=true
